### PR TITLE
Use the fresh versions of dependencies

### PR DESCRIPTION
**Pull request by odisseus**

### CODE REVIEW

**Comment by odisseus** [comment]
It [turned out](https://github.com/multiformats/java-multibase/pull/15#pullrequestreview-427568223) that the issues with this set of projects run much deeper than a simple method rename. I decided to solve them [bottom up](https://github.com/multiformats/java-multibase/pull/16), because I need an up-to-date IPFS interface for the [project](https://github.com/propensive/fury) I'm working at, and i don't feel like linking the entirety of [Peergos](https://github.com/Peergos/Peergos/tree/master/src/peergos/shared/io/ipfs) just for that purpose. Eventually I will get to fix this particular problem as well.

**Comment by odisseus** [comment]
If by "method names changed" you mean the `java.lang.NoSuchMethodError` thrown by many test cases, then what's actually [changed](https://github.com/multiformats/java-multihash/commit/0eb305c02c7778abbb6c0379bea24fe553817f04#diff-58f9bc03a39948e2ccdd38bf29fc6e7aR201) is the signature of `Multihash.deserialize`. The latest version of `java-cid` still expects the old signature, and this causes the errors. They should go away if https://github.com/ipld/java-cid/pull/13 gets merged.

**Comment by autonome** [comment]
Hi @odisseus are you still working on this or can I have others pick it up? Or is it blocked?

**Comment by odisseus** [comment]
I stopped working on my pull requests to this library and its dependencies, because apparently their author lost his interest in maintaining them, and I'm not sure my work has any chance to get into the master branch.

I believe this particular set of changes can be merged right away; however, it will solve just some of the problems, not all of them. In particular, the libraries java-multihash and java-cid need to be updated to use a recent commit of java-multibase (ad627a0872 or later), because that commit fixes a critical bug which is inherited by all the dependent libraries.

**Comment by lidel** [comment]
@odisseus fyi there are open bounties for fixing `java-ipfs-http-client` library now (https://github.com/ipfs-shipyard/java-ipfs-http-client/issues/157#issuecomment-665278162) and we definitely are up for accepting fixes

If you want to claim the bounty, please comment in https://github.com/ipfs-shipyard/java-ipfs-http-client/issues/157#issuecomment-665278162 and provide us with list of all PRs that you are blocked on (Java libs are not actively maintained, but me and @autonome can do some poking/spelunking to unblock you)

**Comment by lidel** [comment]
Superseded by https://github.com/ipfs-shipyard/java-ipfs-http-client/pull/170

**Pull request closed without merging**
