### PR TITLE
The repo is super behind the node, did some updates to make it work again 

### PR DESCRIPTION
**Pull request by andrei-tara**

### CODE REVIEW

**Comment by autonome** [comment]
@ianopolous are you up for reviewing this PR?

**Comment by ianopolous** [comment]
I'm seeing a lot of whitespace and linting changes, changing to your multiaddr implementation (is there a problem with the existing one?) and switching to Jackson for JSON, and using an external rest library. Possibly a bug in Multipart as well with a newline?

What problems are you trying to solve?

**Comment by andrei-tara** [comment]
- switching to Jackson for JSON -> the custom parser was failing on several responses and also was super slow. Switch to Jackson solved all this and improved 10x
-  changing to your multiaddr implementation -> performed an update to make IPNS work again 
- using an external rest library -> yes, HttpConnection is throwing a generic exception when the node is responding anything else besides 200, basically wasn't able to  catch and treat correctly the exception

**Comment by ianopolous** [comment]
Do you have an example of some JSON the parser fails on? I'd be very surprised to see this, as it's been used in diverse environments in production for over 15 years. I'd also be very surprised if json parsing was ever a bottleneck. 

The reason we don't use jackson is to be more flexible and work in more environments. For example there are environments this library can be cross compiled to run in which don't support reflection. This means jackson won't work. 

We can probably expand the http error handling here, but I'd rather not take on an external dependency for something so simple. 

If there is a problem with the multiaddr library then we should fix that in the source library.

**Comment by andrei-tara** [comment]
Yes, just run the tests with latest IPFS implementation :)

**Comment by ianopolous** [comment]
I'm not seeing any JSON parsing errors with the latest kubo (v0.15.0).

**Comment by andrei-tara** [comment]
Maybe it is only on my side, but half of the APITest.java are failing because of the abovementioned problems. 
5 min 48 sec

**Comment by ianopolous** [comment]
There are a bunch of failing tests yes, but none are due to JSON parsing.

**Comment by ianopolous** [comment]
I've updated the multihash library in master, which was the main problem. Though there are still a few failing tests.

**Comment by andrei-tara** [comment]
There are a bunch of failing tests yes, but none are due to JSON parsing.
>> If possible, please go to the reabit hole and try to fix the tests you will see what I mean

**Comment by ianopolous** [comment]
All the tests are now green on master except for 2 pubsub ones which is because the API has changed to be multipart. 

There are no JSON issues.

**Comment by andrei-tara** [comment]
Just ran the tests with latest master code and they are still failing on my side :(

**Comment by ianopolous** [comment]
Which tests are failing apart from the two I mentioned?

**Comment by ianopolous** [comment]
I've updated the pubsub implementation now and all tests are green on master. Definitely no JSON errors. I've also improved the error handling. Are there any remaining issues you are aware of?

**Comment by andrei-tara** [comment]
image

this is how it looks on my side

**Comment by ianopolous** [comment]
How are you running the tests?

I've run them with "mvn test", "ant test", using IntelliJ and on the [github runner](https://github.com/ipfs-shipyard/java-ipfs-http-client/runs/8208431241?check_suite_focus=true), all of which a green.

These are all against kubo v0.15.0.

**Comment by ianopolous** [comment]
What command are you using to run kubo?

**Comment by andrei-tara** [comment]
IPFS is running inside a docker container

**Comment by ianopolous** [comment]
What command is it running in docker to start kubo? Are you using the docker compose file in this repo? That's still on go-ipfs v0.6.0. I'll update it.

**Comment by ianopolous** [comment]
Ok I've done that, are you able to test it (I don't use docker)?

**Comment by andrei-tara** [comment]
Yes, docker compose image: ipfs/kubo:master-2022-09-01-d2c4927

**Comment by ianopolous** [comment]
To run the tests you need a custom run command which enables the experimental pubsub. Like this: https://github.com/ipfs-shipyard/java-ipfs-http-client/blob/master/docker-compose.yml

**Comment by kevodwyer** [comment]
closing as out-of-date

**Pull request closed without merging**
